### ISSUE TITLE
bug:  some requests may be dropped randomly

### ISSUE THREAD

**Issue by venffet** [cloudwebrtc/nats-grpc#16]
Hi all, I found some problems with the following code:    
```go
    stream.msgCh = make(chan *nats.Msg, 1)  
    stream.sub, _ = client.nc.ChanSubscribe(stream.reply, stream.msgCh)
```   
[here](https://github.com/cloudwebrtc/nats-grpc/blob/main/pkg/rpc/client.go#L136)  

the `msgCh` is too small, causing nats goto slowConsumer, and then the request be discarded:   
```go
if sub.mch != nil {
    select {			
    case sub.mch <- m:	
    default:				
        goto slowConsumer			
    }		
}  
```  
codes in   [nats.go](https://github.com/nats-io/nats.go/blob/master/nats.go#L2673)

**Comment by wallyqs** [comment]
yes, a recommended size would be the default for sync subscriptions in NATS, which is 8192:
```
make(chan *nats.Msg, 8192)  
```
